"use client";
import {useState} from 'react';
import {Search,Plus,Waves,Hand,Expand,Shrink,Square,Rotate3D,X,ChevronLeft} from 'lucide-react';
import {ASSET_CATALOG,AssetDefinition} from '@/lib/assets';
import {InfluenceKind} from '@/lib/form-engine';
const fields=[{id:'wave',name:'Ripple',detail:'Travelling surface displacement',icon:Waves},{id:'grip',name:'Grip',detail:'Local contact volume',icon:Hand},{id:'bulge',name:'Bulge',detail:'Add local volume',icon:Expand},{id:'pinch',name:'Pinch',detail:'Remove local volume',icon:Shrink},{id:'flatten',name:'Flatten',detail:'Create a planar region',icon:Square},{id:'twist',name:'Twist',detail:'Rotate a local region',icon:Rotate3D}] as const;
export function AssetBrowser({onAddAsset,onAddField,onClose}:{onAddAsset:(asset:AssetDefinition)=>void;onAddField:(kind:InfluenceKind)=>void;onClose:()=>void}){
 const [tab,setTab]=useState<'assets'|'fields'>('assets'),[query,setQuery]=useState('');const q=query.toLowerCase();
 const assets=ASSET_CATALOG.filter(a=>(a.name+' '+a.category).toLowerCase().includes(q));
 return <section className="asset-browser" aria-label="Asset library"><header><button className="icon-button" aria-label="Back to objects" onClick={onClose}><ChevronLeft size={16}/></button><span>Insert</span><button className="icon-button" aria-label="Close asset library" onClick={onClose}><X size={15}/></button></header><div className="asset-tabs"><button aria-pressed={tab==='assets'} onClick={()=>setTab('assets')}>Assets</button><button aria-pressed={tab==='fields'} onClick={()=>setTab('fields')}>Fields</button></div><label className="asset-search"><Search size={14}/><input aria-label="Search assets and fields" value={query} placeholder="Search" onChange={e=>setQuery(e.target.value)}/></label><div className="asset-results">{tab==='assets'?assets.map(a=><button className="asset-row" key={a.id} onClick={()=>onAddAsset(a)} aria-label={'Insert '+a.name}>{a.thumbnail?<img src={a.thumbnail} alt=""/>:<div className="asset-dimension">{Math.round(a.dimensions[0])}<span>mm</span></div>}<span><strong>{a.name}</strong><small>{a.category}</small></span><Plus size={14}/></button>):fields.filter(f=>(f.name+' '+f.detail).toLowerCase().includes(q)).map(f=><button className="field-insert-row" key={f.id} onClick={()=>onAddField(f.id)} aria-label={'Add '+f.name}><f.icon size={18}/><span><strong>{f.name}</strong><small>{f.detail}</small></span><Plus size={14}/></button>)}{(tab==='assets'?assets.length===0:!fields.some(f=>(f.name+' '+f.detail).toLowerCase().includes(q)))&&<p className="asset-empty">No matching items</p>}</div></section>
}
