import assetCatalog from './asset-catalog.json' with {type:'json'};
import type {PlacedAsset} from './assets';
export type InfluenceKind = 'wave'|'grip'|'bulge'|'pinch'|'flatten'|'twist';
export type Falloff = 'gaussian'|'linear'|'smooth'|'constant';
export type Influence = {id:string;name:string;kind:InfluenceKind;enabled:boolean;strength:number;radius:number;x:number;y:number;z:number;wavelength:number;phase:number;angle:number;falloff:Falloff};
export type FormModel = {version:1;name:string;width:number;height:number;depth:number;softness:number;asymmetry:number;lensSpacing:number;lensRadius:number;protect:boolean;lenses:boolean;shell:boolean;wall:number;usb:boolean;buttons:boolean;fingerGrooves:boolean;assets?:PlacedAsset[];influences:Influence[]};
export type Variant={id:string;name:string;model:FormModel;image?:string};
export type MeshData={positions:Float32Array;normals:Float32Array;indices:Uint32Array;volume:number;bounds:number[]};
export const LIMITS={width:[90,220],height:[45,120],depth:[22,90],softness:[2,24],asymmetry:[-15,15],lensSpacing:[24,70],lensRadius:[8,18],wall:[1.6,6]} as const;
export const DEFAULT_MODEL:FormModel={version:1,name:'Camera study',width:150,height:76,depth:42,softness:12,asymmetry:2,lensSpacing:52,lensRadius:13,protect:true,lenses:true,shell:true,wall:2.6,usb:true,buttons:true,fingerGrooves:true,influences:[{id:'wave-1',name:'Travelling wave',kind:'wave',enabled:true,strength:4.8,radius:140,x:0,y:0,z:21,wavelength:44,phase:103,angle:32,falloff:'gaussian'},{id:'grip-1',name:'Hand-contact mass',kind:'grip',enabled:true,strength:9,radius:35,x:51,y:-2,z:21,wavelength:60,phase:0,angle:0,falloff:'smooth'}]};
export const cloneModel=(m:FormModel):FormModel=>JSON.parse(JSON.stringify(m));
export const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export const lensCenters=(m:FormModel)=>[-m.width*.14-m.lensSpacing/2,-m.width*.14+m.lensSpacing/2];
export function smoothstep(a:number,b:number,x:number){const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)}
export function weight(f:Influence,x:number,y:number,z:number){const dx=x-f.x,dy=y-f.y,dz=(z-f.z)*.6;const d=Math.sqrt(dx*dx+dy*dy+dz*dz)/f.radius;switch(f.falloff){case 'constant':return 1;case 'linear':return Math.max(0,1-d);case 'smooth':return 1-smoothstep(0,1.4,d);default:return Math.exp(-d*d*1.6)}}
export const lensY=(m:FormModel)=>m.height*.13;
export const shutterPosition=(m:FormModel)=>[m.width*.34,m.height/2+1.3,0] as const;
export const portPosition=(m:FormModel)=>[m.width/2,-m.height*.25,-1] as const;
export function protection(m:FormModel,x:number,y:number,z:number){if(!m.protect||!m.lenses)return 1;let result=1;for(const cx of lensCenters(m)){const d=Math.hypot(x-cx,y-lensY(m));result*=smoothstep(m.lensRadius+1,m.lensRadius+22,d)}return result}
// Waves are an explicit deformation. The GPU preview and exported implicit field
// share this mapping; a phase change never requires remeshing the live viewport.
export function rippleOffset(m:FormModel,x:number,y:number,z:number,phaseOverride?:number){
 let sum=0,totalAmplitude=0,first=true;
 for(const f of m.influences){if(f.kind!=='wave')continue;const phase=first&&phaseOverride!==undefined?phaseOverride:f.phase;first=false;if(!f.enabled)continue;totalAmplitude+=Math.abs(f.strength);
  const a=f.angle*Math.PI/180,d=Math.hypot(x-f.x,y-f.y)/f.radius;
  const w=f.falloff==='constant'?1:f.falloff==='linear'?Math.max(0,1-d):f.falloff==='smooth'?1-smoothstep(0,1.4,d):Math.exp(-d*d*1.6);
  sum+=f.strength*w*Math.sin(((x-f.x)*Math.cos(a)+(y-f.y)*Math.sin(a))/f.wavelength*Math.PI*2+phase*Math.PI/180);
 }
 let mask=protection(m,x,y,z);
 if(m.buttons){const p=shutterPosition(m);mask*=smoothstep(9,21,Math.hypot(x-p[0],y-p[1]));}
 if(m.usb){const p=portPosition(m);mask*=smoothstep(8,19,Math.hypot(x-p[0],y-p[1]));}
 // Fade gently at the back; preserve a positive Jacobian even at max amplitude.
 return sum*mask*(.82+.18*Math.tanh(z/Math.max(m.depth,44,totalAmplitude*.36)));
}
export function withoutRipples(m:FormModel):FormModel{const {assets,...geometry}=m;return {...geometry,influences:m.influences.filter(f=>f.kind!=='wave')}}
export function fieldStrength(m:FormModel,x:number,y:number,z:number){let total=0;for(const f of m.influences)if(f.enabled)total+=weight(f,x,y,z)*Math.abs(f.strength);return total*protection(m,x,y,z)}
function roundBox(x:number,y:number,z:number,hx:number,hy:number,hz:number,r:number){const qx=Math.abs(x)-hx+r,qy=Math.abs(y)-hy+r,qz=Math.abs(z)-hz+r;return Math.hypot(Math.max(qx,0),Math.max(qy,0),Math.max(qz,0))+Math.min(Math.max(qx,qy,qz),0)-r}
function cylinderZ(x:number,y:number,z:number,r:number,h:number){const a=Math.hypot(x,y)-r,b=Math.abs(z)-h;return Math.min(Math.max(a,b),0)+Math.hypot(Math.max(a,0),Math.max(b,0))}
function smoothUnion(a:number,b:number,k:number){const h=clamp(.5+.5*(b-a)/k,0,1);return b+(a-b)*h-k*h*(1-h)}
function capsule(x:number,y:number,z:number,ax:number,ay:number,az:number,bx:number,by:number,bz:number,r:number){const vx=x-ax,vy=y-ay,vz=z-az,dx=bx-ax,dy=by-ay,dz=bz-az,t=clamp((vx*dx+vy*dy+vz*dz)/(dx*dx+dy*dy+dz*dz),0,1);return Math.hypot(vx-dx*t,vy-dy*t,vz-dz*t)-r}
export function evaluateBase(m:FormModel,x:number,y:number,z:number){const px=x,py=y,pz=z,protect=protection(m,x,y,z);let radial=0,flattenAmount=0,flattenCentre=0,flattenWeight=0;for(const f of m.influences){if(!f.enabled||f.kind==='wave')continue;const w=weight(f,px,py,pz)*protect,s=f.strength*w;switch(f.kind){case 'grip':z-=s;x-=s*.12;break;case 'bulge':radial+=s;break;case 'pinch':radial-=s;break;case 'flatten':flattenAmount+=s;flattenCentre+=f.z*Math.abs(s);flattenWeight+=Math.abs(s);break;case 'twist':{const a=s*Math.PI/180,yy=y,zz=z;y=yy*Math.cos(a)-zz*Math.sin(a);z=yy*Math.sin(a)+zz*Math.cos(a);break}}}
 if(flattenWeight>0){const plane=flattenCentre/flattenWeight,compression=clamp(flattenAmount/28,-.5,.8);z=plane+(z-plane)/(1-compression)}
 y-=m.asymmetry*(x/m.width)*.25;const r=Math.min(m.softness,m.height/2-1,m.depth/2-1);let exterior=roundBox(x,y,z,m.width/2,m.height/2,m.depth/2,r)-radial;
 if(m.fingerGrooves){for(const yy of [-17,-3,11]){const groove=capsule(px,py,pz,m.width*.30,yy,m.depth/2+13.5,m.width*.51,yy+7,m.depth/2+8.5,5);exterior=-smoothUnion(-exterior,groove,5)}}
 // Annular seats are part of the enclosure, with small edge fillets.
 if(m.lenses){for(const cx of lensCenters(m)){const seat=cylinderZ(px-cx,py-lensY(m),pz-(m.depth/2-2.7),m.lensRadius-.1,2.5)-.6;exterior=smoothUnion(exterior,seat,2.8)}}
 let d=m.shell?Math.max(exterior,-exterior-m.wall):exterior;
 // Subtract apertures AFTER shelling: both connect to the internal cavity.
 if(m.lenses){for(const cx of lensCenters(m)){const bore=cylinderZ(px-cx,py-lensY(m),pz-m.depth/2,m.lensRadius-1,m.depth/2+1);d=Math.max(d,-bore)}}
 if(m.usb){const p=portPosition(m),port=roundBox(px-p[0],py-p[1],pz-p[2],12,1.9,4.8,1.2);d=Math.max(d,-port)}
 if(m.buttons){const p=shutterPosition(m),socket=cylinderZ(px-p[0],pz-p[2],py-p[1],6.6,5);d=Math.max(d,-socket)}
 return d;
}
export function evaluate(m:FormModel,x:number,y:number,z:number){
 if(!m.influences.some(f=>f.kind==='wave'&&f.enabled&&f.strength!==0))return evaluateBase(m,x,y,z);
 // Invert the monotonic Z displacement. Newton converges to sub-micron accuracy.
 let q=z-rippleOffset(m,x,y,z);
 for(let i=0;i<3;i++){const delta=rippleOffset(m,x,y,q),slope=(rippleOffset(m,x,y,q+.01)-delta)/.01;q-=(q+delta-z)/(1+slope)}
 return evaluateBase(m,x,y,q);
}
export function makeInfluence(kind:InfluenceKind):Influence {const names={wave:'Travelling wave',grip:'Grip field',bulge:'Local fullness',pinch:'Local pinch',flatten:'Planar zone',twist:'Local twist'};return {id:kind+'-'+Math.random().toString(36).slice(2,9),name:names[kind],kind,enabled:true,strength:kind==='twist'?18:7,radius:45,x:25,y:0,z:22,wavelength:60,phase:0,angle:0,falloff:'gaussian'}}
export function validateModel(input:unknown):FormModel {if(!input||typeof input!=='object')throw Error('This file does not contain a FORM model.');const raw=input as FormModel;const legacyDefault=raw.wall===undefined&&JSON.stringify(raw)===JSON.stringify({version:1,name:'Camera study',width:158,height:76,depth:44,softness:14,asymmetry:3,lensSpacing:34,lensRadius:13,protect:true,lenses:true,influences:[{id:'wave-1',name:'Travelling wave',kind:'wave',enabled:true,strength:7.5,radius:100,x:16,y:0,z:22,wavelength:61,phase:25,angle:18,falloff:'gaussian'},{id:'grip-1',name:'Hand-contact mass',kind:'grip',enabled:true,strength:12,radius:35,x:54,y:-2,z:22,wavelength:60,phase:0,angle:0,falloff:'smooth'}]});const m={...raw,shell:raw.shell??raw.lenses,wall:raw.wall??2.6,usb:raw.usb??raw.lenses,buttons:raw.buttons??raw.lenses,fingerGrooves:raw.fingerGrooves??raw.lenses};if(m.version!==1||typeof m.name!=='string'||m.name.length>120||!Array.isArray(m.influences)||m.influences.length>20)throw Error('Unsupported model file.');for(const [key,range]of Object.entries(LIMITS)){const val=m[key as keyof typeof LIMITS];if(typeof val!=='number'||!Number.isFinite(val)||val<range[0]||val>range[1])throw Error('Invalid '+key+' value.')}if([m.protect,m.lenses,m.shell,m.usb,m.buttons,m.fingerGrooves].some(v=>typeof v!=='boolean'))throw Error('Invalid region settings.');const ids=new Set<string>(['body','regions','enclosure','canvas']);for(const f of m.influences){if(!f||typeof f.id!=='string'||f.id.length>100||ids.has(f.id)||typeof f.name!=='string'||f.name.length>100||typeof f.enabled!=='boolean'||!['wave','grip','bulge','pinch','flatten','twist'].includes(f.kind)||!['gaussian','linear','smooth','constant'].includes(f.falloff))throw Error('Invalid influence.');ids.add(f.id);const ranges:Record<string,number[]>={strength:[-22,22],radius:[12,160],x:[-120,120],y:[-65,65],z:[-70,70],wavelength:[24,140],phase:[0,360],angle:[-90,90]};for(const [k,r]of Object.entries(ranges)){const v=f[k as keyof Influence];if(typeof v!=='number'||!Number.isFinite(v)||v<r[0]||v>r[1])throw Error('Invalid influence '+k+'.')}}if(m.assets!==undefined){if(!Array.isArray(m.assets)||m.assets.length>80)throw Error('Invalid asset list.');for(const a of m.assets){if(!a||typeof a.id!=='string'||a.id.length>100||ids.has(a.id)||typeof a.sourceId!=='string'||!assetCatalog.some(source=>source.id===a.sourceId)||typeof a.name!=='string'||a.name.length>100||typeof a.visible!=='boolean')throw Error('Invalid asset.');ids.add(a.id);for(const k of ['x','y','z','rx','ry','rz','scale'] as const){if(!Number.isFinite(a[k])||Math.abs(a[k])>(k==='scale'?10:1000)||(k==='scale'&&a[k]<.05))throw Error('Invalid asset transform.')}}}return cloneModel(legacyDefault?DEFAULT_MODEL:m)}
export function generateMesh(m:FormModel,resolution=52):MeshData {const enabled=m.influences.filter(f=>f.enabled),radial=enabled.reduce((v,f)=>v+((f.kind==='bulge'&&f.strength>0)||(f.kind==='pinch'&&f.strength<0)?Math.abs(f.strength):0),0),grip=enabled.reduce((v,f)=>v+(f.kind==='grip'?Math.abs(f.strength):0),0),twist=enabled.some(f=>f.kind==='twist'),flat=enabled.some(f=>f.kind==='flatten'),radialYZ=Math.hypot(m.height/2+radial,m.depth/2+radial+grip),bx=Math.max(m.width/2+radial+grip*.12+4,m.lenses?Math.max(...lensCenters(m).map(Math.abs))+m.lensRadius+4:0),by=Math.max((twist?radialYZ:m.height/2+radial)+Math.abs(m.asymmetry)*.25+4,m.lenses?Math.abs(lensY(m))+m.lensRadius+4:0),bz=Math.max(twist?radialYZ:m.depth/2+radial+grip,flat?105:0)+6;const nx=resolution,ny=Math.max(20,Math.round(resolution*by/bx)),nz=Math.max(20,Math.round(resolution*bz/bx));const sx=2*bx/nx,sy=2*by/ny,sz=2*bz/nz;const row=nx+1,layer=row*(ny+1);const values=new Float32Array(layer*(nz+1));for(let k=0;k<=nz;k++)for(let j=0;j<=ny;j++)for(let i=0;i<=nx;i++){const v=evaluateBase(m,i*sx-bx,j*sy-by,k*sz-bz);values[k*layer+j*row+i]=Math.abs(v)<1e-7?1e-7:v}const positions:number[]=[],normals:number[]=[],indices:number[]=[];const edges=new Map<string,number>();const offsets=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]];const tets=[[0,5,1,6],[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6]];const ids=new Array<number>(8),pts=new Array<number[]>(8);let volume=0;let direction=[0,0,1];
function vertex(a:number,b:number){const ia=ids[a],ib=ids[b],key=ia<ib?ia+':'+ib:ib+':'+ia;const found=edges.get(key);if(found!==undefined)return found;const va=values[ia],vb=values[ib],t=va/(va-vb),pa=pts[a],pb=pts[b];const x=pa[0]+(pb[0]-pa[0])*t,y=pa[1]+(pb[1]-pa[1])*t,z=pa[2]+(pb[2]-pa[2])*t;const n=positions.length/3;positions.push(x,y,z);const e=.06,dx=evaluateBase(m,x+e,y,z)-evaluateBase(m,x-e,y,z),dy=evaluateBase(m,x,y+e,z)-evaluateBase(m,x,y-e,z),dz=evaluateBase(m,x,y,z+e)-evaluateBase(m,x,y,z-e),len=Math.hypot(dx,dy,dz)||1;normals.push(dx/len,dy/len,dz/len);edges.set(key,n);return n}
function triangle(a:number,b:number,c:number){const ax=positions[a*3],ay=positions[a*3+1],az=positions[a*3+2],ux=positions[b*3]-ax,uy=positions[b*3+1]-ay,uz=positions[b*3+2]-az,vx=positions[c*3]-ax,vy=positions[c*3+1]-ay,vz=positions[c*3+2]-az;const cx=uy*vz-uz*vy,cy=uz*vx-ux*vz,cz=ux*vy-uy*vx;if(cx*direction[0]+cy*direction[1]+cz*direction[2]<0){const temp=b;b=c;c=temp}indices.push(a,b,c);const b0=b*3,c0=c*3;volume+=(ax*(positions[b0+1]*positions[c0+2]-positions[b0+2]*positions[c0+1])+ay*(positions[b0+2]*positions[c0]-positions[b0]*positions[c0+2])+az*(positions[b0]*positions[c0+1]-positions[b0+1]*positions[c0]))/6}
for(let k=0;k<nz;k++)for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){let inside=0;for(let c=0;c<8;c++){const o=offsets[c];ids[c]=(k+o[2])*layer+(j+o[1])*row+i+o[0];pts[c]=[(i+o[0])*sx-bx,(j+o[1])*sy-by,(k+o[2])*sz-bz];if(values[ids[c]]<0)inside++}if(inside===0||inside===8)continue;for(const tet of tets){const inn=tet.filter(c=>values[ids[c]]<0),out=tet.filter(c=>values[ids[c]]>=0);if(!inn.length||!out.length)continue;direction=[0,1,2].map(axis=>out.reduce((sum,c)=>sum+pts[c][axis],0)/out.length-inn.reduce((sum,c)=>sum+pts[c][axis],0)/inn.length);if(inn.length===1)triangle(vertex(inn[0],out[0]),vertex(inn[0],out[1]),vertex(inn[0],out[2]));else if(inn.length===3)triangle(vertex(out[0],inn[0]),vertex(out[0],inn[1]),vertex(out[0],inn[2]));else if(inn.length===2){const a=vertex(inn[0],out[0]),b=vertex(inn[0],out[1]),c=vertex(inn[1],out[0]),d=vertex(inn[1],out[1]);triangle(a,b,c);triangle(b,d,c)}}}// Apply the same explicit deformation used by the GPU, including its normal Jacobian.
if(m.influences.some(f=>f.kind==='wave'&&f.enabled)){
 for(let i=0;i<positions.length;i+=3){const x=positions[i],y=positions[i+1],z=positions[i+2],e=.04,d=rippleOffset(m,x,y,z),dx=(rippleOffset(m,x+e,y,z)-rippleOffset(m,x-e,y,z))/(2*e),dy=(rippleOffset(m,x,y+e,z)-rippleOffset(m,x,y-e,z))/(2*e),dz=(rippleOffset(m,x,y,z+e)-rippleOffset(m,x,y,z-e))/(2*e);positions[i+2]+=d;const nx=normals[i]*(1+dz)-normals[i+2]*dx,ny=normals[i+1]*(1+dz)-normals[i+2]*dy,nz=normals[i+2],len=Math.hypot(nx,ny,nz)||1;normals[i]=nx/len;normals[i+1]=ny/len;normals[i+2]=nz/len;}
 volume=0;for(let i=0;i<indices.length;i+=3){const a=indices[i]*3,b=indices[i+1]*3,c=indices[i+2]*3;volume+=(positions[a]*(positions[b+1]*positions[c+2]-positions[b+2]*positions[c+1])+positions[a+1]*(positions[b+2]*positions[c]-positions[b]*positions[c+2])+positions[a+2]*(positions[b]*positions[c+1]-positions[b+1]*positions[c]))/6;}
}
const bounds=positions.length?[Infinity,Infinity,Infinity,-Infinity,-Infinity,-Infinity]:[0,0,0,0,0,0];for(let i=0;i<positions.length;i+=3)for(let a=0;a<3;a++){bounds[a]=Math.min(bounds[a],positions[i+a]);bounds[a+3]=Math.max(bounds[a+3],positions[i+a])}return {positions:new Float32Array(positions),normals:new Float32Array(normals),indices:new Uint32Array(indices),volume:Math.abs(volume),bounds};}
export function sectionContours(m:FormModel,z:number,n=100){const w=m.width+90,h=m.height+70,dx=w/n,dy=h/n;const segments:number[][]=[];const value=(i:number,j:number)=>evaluate(m,i*dx-w/2,j*dy-h/2,z);for(let j=0;j<n;j++)for(let i=0;i<n;i++){const points=[[i*dx-w/2,j*dy-h/2],[(i+1)*dx-w/2,j*dy-h/2],[(i+1)*dx-w/2,(j+1)*dy-h/2],[i*dx-w/2,(j+1)*dy-h/2]];const v=[value(i,j),value(i+1,j),value(i+1,j+1),value(i,j+1)],cuts:number[][]=[];for(let a=0;a<4;a++){const b=(a+1)%4;if((v[a]<0)!==(v[b]<0)){const t=v[a]/(v[a]-v[b]);cuts.push([points[a][0]+t*(points[b][0]-points[a][0]),points[a][1]+t*(points[b][1]-points[a][1])])}}for(let a=0;a<cuts.length-1;a+=2)segments.push([...cuts[a],...cuts[a+1]])}return {segments,width:w,height:h}}
export function silhouettePoints(m:FormModel,n=140){const w=m.width+90,h=m.height+70,d=m.depth/2+60;const points:number[][]=[];for(let j=0;j<n;j++)for(let i=0;i<n;i++){const x=(i/n-.5)*w,y=(j/n-.5)*h;let hit=false;for(let k=0;k<=30;k++){if(evaluate(m,x,y,-d+k*2*d/30)<0){hit=true;break}}if(hit)points.push([x,y])}return {points,width:w,height:h,size:w/n}}
export function binarySTL(data:MeshData){if(!data.indices.length)throw Error('This field has no solid to export.');const count=data.indices.length/3,buffer=new ArrayBuffer(84+count*50),view=new DataView(buffer);const header=new TextEncoder().encode('FORM field sketchbook | millimetres');new Uint8Array(buffer).set(header);view.setUint32(80,count,true);for(let f=0;f<count;f++){const o=84+f*50,ids=[data.indices[f*3],data.indices[f*3+1],data.indices[f*3+2]],p=data.positions;const a=ids[0]*3,b=ids[1]*3,c=ids[2]*3,ux=p[b]-p[a],uy=p[b+1]-p[a+1],uz=p[b+2]-p[a+2],vx=p[c]-p[a],vy=p[c+1]-p[a+1],vz=p[c+2]-p[a+2];const n=[uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx],len=Math.hypot(...n)||1;for(let q=0;q<3;q++)view.setFloat32(o+q*4,n[q]/len,true);for(let v=0;v<3;v++)for(let q=0;q<3;q++)view.setFloat32(o+12+v*12+q*4,p[ids[v]*3+q],true)}return buffer}
