import test from 'node:test';
import assert from 'node:assert/strict';
import {Matrix4,Euler} from 'three';
import {cloneModel,DEFAULT_MODEL,generateMesh,generateMeshAsync,evaluateBase,modelBounds} from '../lib/form-engine.ts';
import {makeShape,compileShape} from '../lib/shapes.ts';
import {createMeshSamplingGrid} from '../lib/mesh-sampling.ts';
import {previewRefinement,previewResolution} from '../lib/preview-scheduler.ts';
import {auditMesh} from '../lib/mesh-audit.ts';
import {createCameraPodStudy} from '../lib/camera-pod-study.ts';
const model=shape=>({...cloneModel(DEFAULT_MODEL),baseEnabled:false,influences:[],asymmetry:0,shapes:[{...makeShape('cylinder'),x:0,y:0,z:0,width:42,height:5,depth:42,rx:90,blend:0,...shape}]});
function error(m,mesh,filter=()=>true){const shapes=m.shapes.map(compileShape),p=mesh.positions;let max=0,sum=0,count=0;for(let i=0;i<mesh.indices.length;i+=3){const ids=Array.from(mesh.indices.slice(i,i+3),v=>v*3),c=[0,1,2].map(a=>ids.reduce((s,v)=>s+p[v+a],0)/3);if(!filter(c))continue;const d=Math.abs(evaluateBase(m,...c,shapes));max=Math.max(max,d);sum+=d;count++;}assert.ok(count>0);return {max,mean:sum/count,count};}
function closed(mesh){const a=auditMesh(mesh);assert.equal(a.components,1);for(const key of ['boundaryEdges','nonManifoldEdges','inconsistentWindingEdges','degenerateTriangles','invalidIndices'])assert.equal(a[key],0,key);assert.equal(a.finite,true);}
test('ordinary thin circular caps resolve their corner without altering authored geometry',()=>{const m=model(),before=JSON.stringify(m),uniform=generateMesh(m,32,undefined,{featurePlanes:false}),aligned=generateMesh(m,32),old=error(m,uniform),now=error(m,aligned);assert.ok(old.max>.3);assert.ok(now.max<.03&&now.max<old.max*.1,JSON.stringify({old,now}));closed(uniform);closed(aligned);assert.equal(aligned.sampling.curvedLayerOffset,.02);assert.equal(JSON.stringify(m),before);});
test('aligned circular layers follow the actual XYZ Euler axis, and arbitrary rotations stay conservative',()=>{for(const rotation of [[0,0,0],[90,0,0],[0,0,90],[90,90,90],[-90,0,0]]){const m=model({rx:rotation[0],ry:rotation[1],rz:rotation[2]}),matrix=new Matrix4().makeRotationFromEuler(new Euler(...rotation.map(v=>v*Math.PI/180),'XYZ')),axis=[matrix.elements[4],matrix.elements[5],matrix.elements[6]].findIndex(v=>Math.abs(v)>1-1e-9),grid=createMeshSamplingGrid(m,modelBounds(m,false),32);assert.ok(axis>=0);for(const face of [-2.5,2.5])for(const offset of [-.02,.02])assert.ok(grid.coordinates[axis].some(v=>Math.abs(v-face-offset)<1e-9));assert.ok(grid.sampling.addedPlanes.every(v=>v<=24));}const longBore=model({height:80});assert.equal(createMeshSamplingGrid(longBore,modelBounds(longBore,false),32).sampling.featureAligned,false,'remote caps of long bores do not consume the feature budget');const tilted=model({rx:31,ry:19,rz:11});assert.equal(createMeshSamplingGrid(tilted,modelBounds(tilted,false),32).sampling.featureAligned,false);});
test('settled circular preview refines automatically and remains abortable during refinement',async()=>{const m=model(),before=JSON.stringify(m);assert.equal(previewRefinement(true),undefined);const draft=generateMesh(m,28),settled=generateMesh(m,28,previewRefinement(false));assert.ok(error(m,settled).max<=error(m,draft).max);assert.ok(settled.refinement,'already accurate circles still use the shared settled pipeline');closed(settled);let ticks=0,meshYields=0;await generateMeshAsync(m,28,undefined,undefined,{budgetMs:1,now:()=>ticks++,yieldControl:async()=>meshYields++});const controller=new AbortController();ticks=0;let yields=0;await assert.rejects(generateMeshAsync(m,28,previewRefinement(false),undefined,{signal:controller.signal,budgetMs:1,now:()=>ticks++,yieldControl:async()=>{if(++yields>meshYields+4)controller.abort();}}),{name:'AbortError'});assert.ok(yields>meshYields,'abort reaches real surface refinement after sampling completes');assert.equal(JSON.stringify(m),before);});
test('real camera lens rim becomes materially smoother under the ordinary settled policy',()=>{const m=createCameraPodStudy(),before=JSON.stringify(m),rim=([x,y,z])=>z>15&&Math.hypot(x+4,y+37.5)>18&&Math.hypot(x+4,y+37.5)<23,old=error(m,generateMesh(m,90,undefined,{featurePlanes:false}),rim),mesh=generateMesh(m,previewResolution(m,{mobile:false,editing:false}),previewRefinement(false)),now=error(m,mesh,rim);assert.ok(now.mean<old.mean*.4,JSON.stringify({old,now}));assert.ok(now.max<old.max);closed(mesh);assert.equal(JSON.stringify(m),before);console.log(JSON.stringify({cameraRim:{old,now},triangles:mesh.indices.length/3,qualityLimited:mesh.refinement.qualityLimited}));});
