import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';
import vm from 'node:vm';
async function harness(){const script=await readFile('out/sw.js','utf8'),handlers={},stores=new Map();let offline=false,failed=false,claimed=false;const key=request=>typeof request==='string'?new URL(request,'https://form.test').href:request.url;const cache=name=>{if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return {addAll:async urls=>{for(const url of urls)store.set(key(url),new Response('asset '+url,{headers:{'content-type':url==='/'?'text/html':'application/octet-stream'}}))},put:async(request,response)=>store.set(key(request),response),match:async request=>store.get(key(request))?.clone()}};const context={URL,Response,Error,self:{location:{origin:'https://form.test'},addEventListener:(name,handler)=>handlers[name]=handler,skipWaiting:async()=>{},clients:{claim:async()=>{claimed=true},matchAll:async()=>[]}},caches:{open:async name=>cache(name),keys:async()=>[...stores.keys()],delete:async name=>stores.delete(name),match:async request=>{for(const store of stores.values())if(store.has(key(request)))return store.get(key(request)).clone()}},fetch:async()=>{if(offline)throw Error('offline');return new Response(failed?'error':'online shell',{status:failed?503:200,headers:{'content-type':'text/html'}})}};vm.runInNewContext(script,context);let install;handlers.install({waitUntil:p=>install=p});await install;let activation;handlers.activate({waitUntil:p=>activation=p});await activation;const request=async(path,mode='navigate')=>{let response;handlers.fetch({request:{url:'https://form.test'+path,method:'GET',mode},respondWith:p=>response=p});return response?await response:undefined};return {script,request,stores,setOffline:v=>offline=v,setFailed:v=>failed=v,claimed}}
test('exported shell includes iOS metadata and all precached assets exist',async()=>{const h=await harness(),html=await readFile('out/index.html','utf8');assert.match(html,/viewport-fit=cover/);assert.ok(html.includes('name="mobile-web-app-capable" content="yes"'));assert.match(html,/manifest.webmanifest/);assert.match(html,/apple-touch.png/);const list=JSON.parse(h.script.match(/const ASSETS=(\[[^;]+\]);/)[1]);assert.ok(list.some(x=>x.endsWith('.woff2')));assert.ok(list.some(x=>x.includes('/_next/static/')&&x.endsWith('.js')));for(const url of list)await access('out'+(url==='/'?'/index.html':url));assert.equal(h.claimed,true)});
test('offline and failed navigation return the cached shell',async()=>{const h=await harness();h.setOffline(true);assert.match(await (await h.request('/')).text(),/asset/);h.setOffline(false);h.setFailed(true);assert.match(await (await h.request('/')).text(),/asset/)});
test('offline fonts and geometry worker chunks stay available; data requests bypass cache',async()=>{const h=await harness(),urls=JSON.parse(h.script.match(/const ASSETS=(\[[^;]+\]);/)[1]);h.setOffline(true);for(const url of urls.filter(x=>x.endsWith('.woff2')||x.endsWith('.js')))assert.equal((await h.request(url,'cors')).ok,true);assert.equal(await h.request('/api/private','cors'),undefined)});
test('an open previous version can retrieve its immutable chunks',async()=>{const h=await harness();h.stores.set('form-static-older',new Map([['https://form.test/_next/static/old.js',new Response('previous chunk')]]));h.setOffline(true);assert.equal(await (await h.request('/_next/static/old.js','cors')).text(),'previous chunk')});

test('component GLBs load on demand and remain available offline after use',async()=>{
 const h=await harness(),urls=JSON.parse(h.script.match(/const ASSETS=(\[[^;]+\]);/)[1]);
 assert.equal(urls.some(url=>url.endsWith('.glb')),false);
 assert.ok(urls.some(url=>url.startsWith('/assets/components/')&&url.endsWith('.png')));
 const path='/assets/components/pololu-usb-c.glb';
 assert.equal(await (await h.request(path,'cors')).text(),'online shell');
 h.setOffline(true);assert.equal(await (await h.request(path,'cors')).text(),'online shell');
});
